[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.17"
# optimizer = true
# optimizer_runs = 200
remappings=["@openzeppelin/=node_modules/@openzeppelin"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
